count: 3
dt: 0.2

display:
  width: 1200
  height: 800
  color: "#000022"

sun:
  radius: 10
  weight: 100
  color: "yellow"
  speed_x: 0
  speed_y: 0.4

planet-1:
  width: 20
  height: 20
  radius: 5
  color: "green"
  x: 300
  y: 300
  weight: 2
  speed_x: 0
  speed_y: 0.4

comet:
  width: 20
  height: 20
  radius: 3
  color: "red"
  x: 200
  y: 200
  weight: 1
  speed_x: 0
  speed_y: 0.4